export { default as Footer } from "./footer"
export { default as Header } from "./header"
export { default as Markdown } from "./markdown"
export { default as Heading } from "./heading"
export { default as Resolver } from "./resolver"
export { default as Image } from "./image"
export type { ImageProps } from "./image"
export { default as LastModified } from "./last-modified"
export type { LastModifiedProps } from "./last-modified"
export { default as Link } from "./link"
export type { LinkProps } from "./link"
export {
    default as DynamicPageComponent,
    generateMetadata,
} from "./dynamic-page-component"
export { default as ObjectComponent } from "./object"
export type { ObjectComponentProps } from "./object"
export { default as TagManager } from "./tag-manager"
export { default as CurrentVersion } from "./current-version"
export { default as Code } from "./code"
export { default as DevTools } from "./dev-tools"
