console.info("using firestore mock")

const backupData = {
    content: {
        text: `
# This is the backup text
## Use standard markdown syntax to edit this backup stuff
### h2 components have copy buttons for backup
`,
    },
}

const data = {
    test: {
        data: {
            title: "very important data",
            important: true,
        },
    },
    home: {
        content: {
            text: `
# This is text generated by the firestore mock
## Use standard markdown syntax to edit this text
### h2 components have copy buttons
`,
        },
    },
}

class Firestore {
    collection(collectionName) {
        return {
            doc: (docName) => {
                return {
                    get: async () => {
                        return {
                            data: () =>
                                data[collectionName][docName] || data[docName],
                        }
                    },
                }
            },
        }
    }

    doc(docName) {
        const splitKeyArray = docName.split("/")
        let tempData = data

        for (const key of splitKeyArray) {
            tempData = tempData[key]
            if (tempData === undefined) {
                tempData = backupData[key]
                break
            }
        }

        return {
            get: async () => {
                return {
                    data: () => tempData,
                }
            },
        }
    }
}

module.exports = { Firestore }
