console.info("using firestore mock")

const data = {
    test: {
        data: {
            title: "very important data",
            important: true,
        },
    },
    home: {
        content: { text: "# This is text generated by the firestore mock" },
    },
}

class Firestore {
    collection(collectionName) {
        return {
            doc: (docName) => {
                return {
                    get: async () => {
                        return {
                            data: () => data[collectionName][docName],
                        }
                    },
                }
            },
        }
    }

    doc(docName) {
        const splitKeyArray = docName.split("/")
        let tempData = data

        for (const key of splitKeyArray) {
            tempData = tempData[key]
            if (tempData === undefined) break
        }

        return {
            get: async () => {
                return {
                    data: () => tempData,
                }
            },
        }
    }
}

module.exports = { Firestore }
