export { default as ColorSwitcher } from "./color-switcher"
export { default as ReduceMotion } from "./reduce-motion"
export { default as Footer } from "./footer"
export { default as Header } from "./header"
export { default as UserSettings } from "./user-settings"
export { default as LayoutZoom } from "./layout-zoom"
export { default as PinchZoom } from "./pinch-zoom"
