export { default as ColorSwitcher } from "./color-switcher"
export { default as ReduceMotion } from "./reduce-motion"
export { default as Footer } from "./footer"
export { default as Header } from "./header"
export { default as UserSettings } from "./user-settings"
export { default as LayoutZoom } from "./layout-zoom"
export { default as PinchZoom } from "./pinch-zoom"
export { default as Markdown } from "./markdown"
export { default as Heading } from "./heading"
export { default as Resolver } from "./resolver"
export { default as Image } from "./image"
export type { ImageProps } from "./image"
export { default as LastModified } from "./last-modified"
export type { LastModifiedProps } from "./last-modified"
export { default as ReadPercentage } from "./read-percentage"
export { default as Link } from "./link"
export type { LinkProps } from "./link"
export {
    default as DynamicPageComponent,
    generateDynamicMetadata,
} from "./dynamic-page-component"
export { default as ObjectComponent } from "./object"
export type { ObjectComponentProps } from "./object"
